```{r ch2-setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Building basic visualizations with ggplot2 {#building-basic-visualizations}

```{r, include=FALSE}

source('data/affinity_spending/load_affinity_spending.R')

affinity_spending_cat_monthly <- affinity_spending_cat %>%
  dplyr::filter(!provisional) %>%
  mutate(year_month = paste0(year(date),"-", str_pad(month(date), 2, pad="0"))) %>%
  group_by(year_month, spending_category, income_quartile) %>%
  summarise(med_spending_prop = median(spending_prop_vs_jan_2020, na.rm=T), .groups = "drop")

```

```{r}

ggplot(affinity_spending_cat_monthly %>% 
         pivot_wider(names_from = spending_category, 
                     values_from = med_spending_prop), 
       aes(x = durables, y = nondurables, color = income_quartile)) +
  geom_point() +
  geom_path()

```


## Basic ggplot2 syntax

```{r, echo=FALSE}

ggplot(tibble()) + 
  geom_point() + 
  xlim(0, 100) + 
  ylim(38, 78) +
  coord_equal() +
  annotate("rect", xmin = 70, xmax = 100, ymin = 38, 
           ymax = 71, fill = "white", color = "black") +
  annotate("text", x = 85, y = 75, label = "plot", size = 8) +
  annotate("text", x = 85, y = 68, label = "geom", size = 6) +
  annotate("text", x = 85, y = 64, label = "(chart type or shape)", size = 3) +
  annotate("segment", x = 85, xend = 85, y = 62, yend = 52, 
           arrow = arrow(type = "closed", length = unit(.13, "inches"))) +
  annotate("text", x = 85, y = 49, label = "aesthetics", size = 6) +
  annotate("text", x = 85, y = 43, label = "(visual properties,\nlike x position, color)", 
           size = 3) +
  annotate("text", x = 54, y = 49, label = "mapping", size = 6) +
  annotate("segment", x = 63, xend = 74, y = 48.5, yend = 48.5, 
           arrow = arrow(type = "closed", length = unit(.13, "inches"))) +
  annotate("text", x = 17, y = 75, label = "data", size = 8) +
  annotate("rect", xmin = 0, xmax = 33, ymin = 38, 
           ymax = 71, fill = "white") +
  annotate("rect", xmin = 1, xmax = 8, ymin = 63, 
           ymax = 70, fill = "grey60") +
  annotate("rect", xmin = 9, xmax = 16, ymin = 63, 
           ymax = 70, fill = "grey60") +
  annotate("rect", xmin = 17, xmax = 24, ymin = 63, 
           ymax = 70, fill = "grey60") +
  annotate("rect", xmin = 25, xmax = 32, ymin = 63, 
           ymax = 70, fill = "grey60") +
  annotate("rect", xmin = 1, xmax = 8, ymin = 55, 
           ymax = 62, fill = "grey90") +
  annotate("rect", xmin = 9, xmax = 16, ymin = 55, 
           ymax = 62, fill = "grey90") +
  annotate("rect", xmin = 17, xmax = 24, ymin = 55, 
           ymax = 62, fill = "grey90") +
  annotate("rect", xmin = 25, xmax = 32, ymin = 55, 
           ymax = 62, fill = "grey90") +
  annotate("rect", xmin = 1, xmax = 8, ymin = 47, 
           ymax = 54, fill = "grey80") +
  annotate("rect", xmin = 9, xmax = 16, ymin = 47, 
           ymax = 54, fill = "grey80") +
  annotate("rect", xmin = 17, xmax = 24, ymin = 47, 
           ymax = 54, fill = "grey80") +
  annotate("rect", xmin = 25, xmax = 32, ymin = 47, 
           ymax = 54, fill = "grey80") +
  annotate("rect", xmin = 1, xmax = 8, ymin = 39, 
           ymax = 46, fill = "grey90") +
  annotate("rect", xmin = 9, xmax = 16, ymin = 39, 
           ymax = 46, fill = "grey90") +
  annotate("rect", xmin = 17, xmax = 24, ymin = 39, 
           ymax = 46, fill = "grey90") +
  annotate("rect", xmin = 25, xmax = 32, ymin = 39, 
           ymax = 46, fill = "grey90") +
  annotate("segment", x = 45, xend = 34, y = 48.5, yend = 48.5, 
           arrow = arrow(type = "closed", length = unit(.13, "inches"))) +
  theme_void()

  



```



### Add Main Plot Function

### Set the Data

### Choose a shape layer

### Map Variables to Aesthetics

### Add Non-Variable Adjustments

### Simple Plot Template

```{r, eval=FALSE}

# start with the main plot function and set the data frame
ggplot(data = data_frame) + 
  
# next add a geometry layer and create the mapping between data frame and aesthetics
  geom_...(mapping = aes(aesthetics1 = data_field1, aesthetics2 = data_field))

```

### Inheritance



### How to Debug Code
